---
apiVersion: v1
kind: Service
metadata:
  name: hub-frontend--nodeport
  labels:
    app: hub-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080 # You can specify a port in the range 30000-32767 or let Kubernetes assign one automatically
      name: frontend
      protocol: TCP
  selector:
    app: hub-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: hub-api-nodeport
  labels:
    app: hub-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 32081 # You can specify a port in the range 30000-32767 or let Kubernetes assign one automatically
      name: backend
      protocol: TCP
  selector:
    app: hub-api