apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-layout-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ssd-hostpath
