metadata:
  name: standalone
resources:
  - ../../base

helmCharts:
  - name: hub
    releaseName: hub
    namespace: kerberos-hub
    repo: https://charts.kerberos.io
    valuesFile: ../../base/hub/kerberos-hub-values.yaml
    valuesInline:
        kerberoshub:
          api:
            url: "localhost:32081"
  - name: openebs
    releaseName: openebs
    repo: https://openebs.github.io/charts
  - name: mongodb
    releaseName: mongodb
    namespace: mongodb
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: ../../base/mongodb/mongodb-values.yaml
  - name: rabbitmq
    releaseName: rabbitmq
    namespace: rabbitmq
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: ../../base/rabbitmq/rabbitmq-values.yaml
  - name: vernemq
    releaseName: vernemq
    namespace: vernemq
    repo: https://vernemq.github.io/docker-vernemq
    valuesFile: ../../base/vernemq/vernemq-values.yaml