resources:
- mongodb-configmap.yaml
- factory/kerberos-factory-deployment.yaml
- factory/kerberos-factory-service.yaml
- factory/kerberos-factory-clusterrole.yaml
- vault/kerberos-vault-deployment.yaml
- vault/kerberos-vault-service.yaml

helmCharts:
  - name: mongodb
    releaseName: mongodb  
    repo: https://charts.bitnami.com/bitnami
    valuesFile: mongodb-values.yaml