apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent1
  labels:
    name: agent1
spec:
  selector:
    matchLabels:
      app: agent1
  replicas: 1
  template:
    metadata:
      labels:
        app: agent1
    spec:
      containers:
        - name: agent1
          image: kerberos/agent:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: AGENT_KEY
              value: demo-agent1
            - name: AGENT_NAME
              value: demo-agent1
            - name: AGENT_CAPTURE_IPCAMERA_RTSP
              value: rtsp://fake.kerberos.io/stream
            - name: AGENT_CAPTURE_IPCAMERA_SUB_RTSP
              value: rtsp://fake.kerberos.io/stream
            - name: AGENT_CLOUD	
              value: kstorage
            - name: AGENT_KERBEROSVAULT_URI	
              #value: http://vault-lb.kerberos-vault/api
              value: http://vault-nodeport.kerberos-vault:80/api
            - name: AGENT_KERBEROSVAULT_ACCESS_KEY	
              value: XJoi2@bgSOvOYBy#
            - name: AGENT_KERBEROSVAULT_SECRET_KEY		
              value: OGGqat4lXRpL@9XBYc8FUaId@5
            - name: AGENT_KERBEROSVAULT_PROVIDER		
              value: minio
            - name: AGENT_KERBEROSVAULT_DIRECTORY		
              value: youruser
            - name: AGENT_CAPTURE_CONTINUOUS
              value: "true"
            - name: AGENT_HUB_URI	
              value: http://hub-api-svc.kerberos-hub:8081 # or your own hub installation
            - name: AGENT_HUB_KEY
              value: AKIAxxxxxxG5Q
            - name: AGENT_HUB_PRIVATE_KEY
              value: K6rRLBI1xxxCk3C1H
            - name: AGENT_MQTT_URI	
              value: tcp://localhost:31883
            - name: AGENT_MQTT_USERNAME
              value: yourusername
            - name: AGENT_MQTT_PASSWORD
              value: yourpassword
            - name: AGENT_TURN_URI
              value: turn:localhost:8443
            - name: AGENT_TURN_USERNAME
              value: username1
            - name: AGENT_TURN_PASSWORD
              value: password1
            # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: agent-svc
#  labels:
#    name: agent-svc
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 80
#  selector:
#    app: agent